SUEPPhysics/SUEPCoffea_dask

runner.py
Fixes the substitution for `xrootd.cmsaf.mit.edu` by `xcache`.
@chadfreer
=> Fix xcache substitution for coffea-casa

condor_SUEP_WS.py, filelist/SUEP_files_simple.json, runner.py, workflows/SUEP_coffea.py, workflows/SumWeights.py
modified:   condor_SUEP_WS.py
modified:   filelist/SUEP_files_simple.json
modified:   runner.py
modified:   workflows/SumWeights.py
=> Add parquet readout. Prepare for kraken running (alternative to Dask)

condor_SUEP_WS.py
=> allow to run on data with isMC=0

condor_SUEP_WS.py, kraken_run.py
modified:   condor_SUEP_WS.py
modified:   kraken_run.py
=> changes to run with xrootd in singularity

kraken_run.py, monitor.py
modified:   kraken_run.py
new file:   monitor.py
=> adding monitoring and resubmission

workflows/SUEP_coffea.py
=> Add in different track collections

workflows/SUEP_coffea.py
Script shouldn't break when there are events with no or few tracks that pass the cuts. Started being an issue when we switched to IsoTracks and LostTracks.
=> Low Track Events Bug

condor_SUEP_WS.py, workflows/SUEP_coffea.py, workflows/SumWeights.py
modified:   condor_SUEP_WS.py
modified:   workflows/SumWeights.py
=> change to xsec (no longer need SumWeights)

workflows/SUEP_coffea.py
=> Cleaning the SUEP producer up

monitor.py, plotting/make_plots.py, workflows/SUEP_coffea.py
modified:   monitor.py
modified:   plotting/make_plots.py
=> Add HLT Paths. Addition to Monitor. Add root output plotting

lxplus_run.py
=> run on lxplus

ben_run.py
=> script for Ben

plotting/make_plots.py
Reverts SUEPPhysics/SUEPCoffea_dask#45
=> Revert "adding plots from PV cut analysis"

kraken_run.py
I'm not sure what I'm supposed to write here. kraken_run.py should now detect who is running it and work for any of us without needing to be modified.
=> kraken_run detects user name instead of needing to be modified

condor_SUEP_WS.py, kraken_run.py, monitor.py
modified:   condor_SUEP_WS.py
modified:   kraken_run.py
modified:   monitor.py
=> Second playing with the memory

workflows/SUEP_coffea.py
- added track selections (vertex and charge)
- fixed some issues where the eigenvalues wouldn't converge for ISR, I think because it didn't have enough tracks
=> Scuoting fixes

workflows/SUEP_coffea.py
=> Fix to scouting normalization

data/xsections_2016.json, data/xsections_2017.json, data/xsections_2018.json
modified:   data/xsections_2016.json
modified:   data/xsections_2017.json
modified:   data/xsections_2018.json
=> adding scouting xsecs

workflows/SUEP_coffea.py
=> Minor fix for scouting

plotting/make_plots.py, plotting/merge_plots.py, workflows/ML_coffea.py, workflows/SUEP_coffea.py, workflows/jetmet_utils.py, workflows/merger.py
- ML conversion scripts had a couple bugs, fixed
- added a merge for the ML conversion
- fixed a bug in the JEC systematics
- some other minor changes in the code
=> some bug fixes

workflows/CMS_corrections/Prefire_utils.py, workflows/SUEP_coffea.py
new file:   workflows/CMS_corrections/Prefire_utils.py
=> adding in prefire utils (Need A02 to run)

plotting/plot_utils.py
Based off the work from Pieter in SUEPLimits, updated plot_ratio:
1. take any # of histograms
2. automatically adjust plot ranges
3. plot them as histograms
4. plot their ratios, with correct ratio uncertainty procedure, based on Hist
=> new plot_ratio with correct uncertanties

plotting/make_plots.py, workflows/README.md
modified:   plotting/make_plots.py
=> add prefire weights to the make_plots

additional_tools/systematic_plots/pu_weight.ipynb
modified:   additional_tools/systematic_plots/pu_weight.ipynb
=> minor cleaning

condor_SUEP_WS.py, plotting/fill_utils.py, plotting/make_plots.py, workflows/CMS_corrections/PartonShower_utils.py, workflows/CMS_corrections/Prefire_utils.py, workflows/SUEP_coffea.py, workflows/SUEP_utils.py, workflows/pandas_accumulator.py, workflows/pandas_utils.py
Finished @chrispap95's pandas accumulator and implemented it in our coffea code.
I've tested the script after implementing it, and all histograms are exactly identical as they are before.
This removes the need for the merger.py script, as we can rely on coffea to merge the chunks' accumulators, each of which is a pandas dataframe.
The metadata and event variables are saved through different accumulators, but are then saved together in an hdf5 file, as before, in the condor_SUEP_WS.py script.
=> Pandas accumulator

.pre-commit-config.yaml, condor_ML.py, condor_SUEP_WS.py, condor_Scouting.py, dask/runner.py, kraken_run.py, plotting/CMS_corrections/GNN_syst.py, plotting/fill_utils.py, plotting/make_plots.py, plotting/merge_plots.py, plotting/multithread.py, plotting/plot_utils.py, resubmit.py, workflows/CMS_corrections/PartonShower_utils.py, workflows/CMS_corrections/Prefire_utils.py, workflows/ML_utils.py, workflows/SUEP_coffea.py, workflows/SUEP_utils.py, workflows/ZH_utils.py, workflows/merger.py, workflows/root_rewrite.py
This update is mainly about improvements in `dask/runner.py`. I switched over from `run_uproot_job`, simplified some parts, and made other improvements in various parts.
I also simplified the logic in the output section of the processor. The code that I removed was basically obsolete after the switch to the pandas accumulator. The only part that remains is an option for dask dataframes but I am considering dropping this as well in the next PR.
**Edit:** I added the new pre-commit updates manually here because the old update committed updates to the master branch and then it became a mess.
=> Dask runner update 

workflows/SUEP_coffea.py
=> added MET filters

plotting/make_plots.py, workflows/SUEP_coffea.py
We were not scaling each event by genWeight when plotting. Not sure about the effect this will have, but all events I've checked have the weight set to 1.
=> added genweight for MC

workflows/SUEP_coffea.py
=> Adding run number to the HEM veto

README.md, kraken_run.py, monitor.py, workflows/SUEP_coffea.py
1. Changed the kranken_run.py to enable processing the private samples of signals in scouting.
2. The current program is broken when processing the scouting signal. It tries to store the SUEP_genMass/Pt/Eta/Phi variables from the gen_mass/pt/phi/eta branches, which are the kinematics of all the generated particles instead of the SUEP scalar. I changed the `workflows/SUEP_coffea.py` to process the scalar_m/pt/phi/eta branches.
=> Scouting signal debugging

plotting/make_plots.py, workflows/SUEP_coffea.py
Modified the track eta selection and ak4jet eta selection (for ht calculation) to match the criteria in the scouting AN.
Added the plotting config for the ABCD method in scouting.
=> scouting selection

workflows/CMS_corrections/jetmet_utils.py
There is a bug in the JEC of the scouting code: somehow the JEC did not run properly (might be) because of a wrong input type of jet kinematics (type=<class 'vector.backends.awkward.MomentumArray4D'>). I fixed it by changing the input type according to what is done in the offline code, which is taken from the events.Jet (type=<class 'vector.backends.awkward.MomentumArray4D'>). Now the ht_JEC is similar to ht, tested on small samples.
=> debug the JEC

workflows/CMS_corrections/PartonShower_utils.py
modified:   workflows/CMS_corrections/PartonShower_utils.py
=> fix to the scouting parton shower weights

filelist/list_2016_scout_data.txt, filelist/list_2017_scout_data.txt, filelist/list_2018_scout_data.txt, kraken_run.py, plotting/plot_utils.py, workflows/CMS_corrections/PartonShower_utils.py
Change the data file name from PFCommissioning to PFHT
Add the normalization to the luminosity of scouting data in the plotting part.
=> Fix filelist

workflows/SUEP_coffea.py
I added the cut on the HLT triggers for the scouting part, similar to what is done in the previous program: https://github.com/tresreid/SUEPs/blob/d5005c05153ee1eb16da2997f80bf30d961e5ca2/scouting/workflow/getArrays.py#L127
=> add HLT trigger selection on scouting

plotting/README.md, plotting/fill_utils.py, resubmit.py, workflows/SUEP_coffea.py, workflows/SUEP_coffea_ZH.py
modified:   plotting/README.md
modified:   plotting/fill_utils.py
modified:   resubmit.py
modified:   workflows/SUEP_coffea_ZH.py
=> fixes to pass pre-commit

kraken_run.py, setup.sh
defines the base directories (MIT system only, but easily configurable for others), and defines suepRun to run with singularity a script.
=> setup.sh script

condor_SUEP_WH.py, kraken_run.py, setup.sh, workflows/SUEP_coffea_WH.py
TODO: need to add option regarding the writeout of the cutflows file.
=> Add cutflows to the condor 

workflows/CMS_corrections/jetmet_utils.py, workflows/SUEP_coffea.py, workflows/SUEP_coffea_WH.py, workflows/SUEP_coffea_ZH.py, workflows/WH_utils.py
modified:   workflows/CMS_corrections/jetmet_utils.py
modified:   workflows/SUEP_coffea_WH.py
modified:   workflows/SUEP_coffea_ZH.py
modified:   workflows/WH_utils.py
=> Adding in the different types of MET and the uncertainties

plotting/merge_plots.py, plotting/submit.py
The job submission had a problem with proxy when running jobs in slurm.
I fixed it by exporting the proxy path in the slurm job scripts.
=> fix the job submissions to slurm

data/xsections_2016.json, data/xsections_2016apv.json, data/xsections_2017.json, data/xsections_2018.json
modified:   data/xsections_2016.json
modified:   data/xsections_2016apv.json
modified:   data/xsections_2017.json
modified:   data/xsections_2018.json
=> adding in the GJets xsections

data/xsections_SUEP.json
- added high mS SUEP xsecs
- added high mS SUEP filter efficiencies calculated using additional_tools/getFilterEffFromLogs.py using the 2016 private samples' logs
=> added high mS SUEP xsecs

kraken_run.py, plotting/CMS_corrections/triggerSF.py, workflows/SUEP_coffea.py
The PFCand and Jets collections in 2016 scouting MC files are empty. I changed the program to process the offlineTracks and OffJets instead.
=> Fix 2016 mc

additional_tools/eventDisplay.py, plotting/make_plots.py, workflows/SUEP_coffea.py, workflows/SUEP_coffea_WH.py
- added event, run, lumiblock for WH and ggF offline & scouting
- minor changes to eventDisplays we made for the PAS for offline
=> Event info

workflows/SUEP_coffea_WH.py, workflows/WH_utils.py
- updated W_kinematics function (returns W mT, pT, phi) so producer code is more self-consistent
=> W_kinematics function update

histmaker/fill_utils.py, histmaker/make_hists.py
- New features in make_hists.py
- Now adds cutflows from new ntuples
- Cutflows updated with selections applied in make_hists
- Added git commit and git diff
=> Cutflows in histmaker

condor_SUEP_WH.py, histmaker/fill_utils.py, histmaker/make_hists.py, workflows/SUEP_coffea_WH.py, workflows/utils/pandas_utils.py
- added format metadata function so stored cutflows are floats not value_accumulators
- cutflows' keys in the metadata dict now called cutflow_*
- fixed bug in form_metadata function
=> Cutflow and metadata updates at producer level

environment.yml, histmaker/fill_utils.py, histmaker/make_hists.py, workflows/SUEP_coffea_WH.py
- added vector, fastjet to env, closes #306 
- fixed cutflows counting and normalization in histmaker
- added cutflow count after the one cluster selection in ntuplemaker
=> Cutflow fixes & Env fixes

data/xsections_2016.json, data/xsections_2016apv.json, data/xsections_2017.json, data/xsections_2018.json, workflows/SUEP_coffea_WH.py, workflows/WH_utils.py
- added photon variables
- added ak4jets in SUEP sample
- added gen cuts for WJets inclusive sample
- implemented kr factor for WJets inclusive sample
- ignore performance warning
- removed deltaR, deltaPhi variables from ntuplemaker, can be made on the fly in make_hists.py
=> Ntuplemaker updates

workflows/CMS_corrections/golden_jsons_utils.py, workflows/CMS_corrections/jetmet_utils.py
modified:   workflows/CMS_corrections/golden_jsons_utils.py
modified:   workflows/CMS_corrections/jetmet_utils.py
=> Fixing mistakes in CMS corrections

workflows/SUEP_coffea_WH.py, workflows/WH_utils.py
- added jet ID to the WH utils
- added new variables to the WH ntuplemaker
=> new variables, jet id

histmaker/make_hists.py, workflows/CMS_corrections/jetmet_utils.py, workflows/SUEP_coffea_WH.py
- blind the WH histmaker for data, for now with conservative region of # const > 40 and S1 > 0.5
- fix a minor bug that made data crash in the WH ntuplemaker, when the code tried to count the dark pseudoscalars in signal MC
- typecast and exceptions added in the jetmet utils to add robustness to the code
- some WH variables in the histmaker were inconsistent with the current ntuplemaker, those have been fixed
=> WH Data Running
